# Generated by Django 4.0.5 on 2022-06-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_dinner', models.CharField(max_length=250)),
                ('price_dinner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_food', models.CharField(max_length=50)),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('image', models.ImageField(default='null', upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='pasta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typepasta', models.CharField(max_length=100)),
                ('pricepasta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='salads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typesalads', models.CharField(max_length=100)),
                ('pricesalads', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typesubs', models.CharField(max_length=250)),
                ('pricesubs', models.IntegerField()),
                ('priceSsubs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('toppins', models.CharField(max_length=250)),
            ],
        ),
    ]
